services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=bts-backend-test'
      - 'POSTGRES_PASSWORD=bts-backend-test'
      - 'POSTGRES_USER=bts-backend-test'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    ports:
      - '5434:5432'
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data/pgdata
      - ./:/docker-entrypoint-initdb.d/
